# 应用服务 WEB 访问端口
server:
  port: 8080
  servlet:
    context-path: /data-migration
logging:
  level:
    com.baomidou.mybatisplus: INFO
    org.apache.ibatis: INFO
    direction.datamigration.**.mapper: INFO

# 数据源配置
spring:
  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          url: jdbc:mysql://logdatabase_IP:log_Port/migration_log?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: username
          password: password
        source1:
          url: jdbc:mysql://source1_IP:source1_Port/source1_database?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: username
          password: password
        source2:
          url: jdbc:mysql://source2_IP:3306/source2_database?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
          username: username
          password: password
  # Flyway 配置
  flyway:
    enabled: true  # 启用 Flyway
    baseline-on-migrate: true  # 非空数据库初始化时执行基线迁移
    baseline-version: 1  # 基线版本号
    locations: classpath:db/init  # 迁移脚本存放路径
    clean-disabled: true  # 禁用清理操作（生产环境必备，防止误删数据）
    validate-on-migrate: true  # 迁移时验证脚本
    encoding: UTF-8  # 脚本编码

# MyBatis-Plus 配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml  # Mapper XML 文件路径
  type-aliases-package: fun.filemigration.**.entity  # 实体类包路径
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 打印SQL日志
  global-config:
    db-config:
      id-type: ASSIGN_ID  # 全局使用雪花 ID 生成策略
    banner: false  # 关闭启动 banner

dromara:
  x-file-storage: #文件存储配置
    default-platform: fastdfs-1 #默认使用的存储平台
    thumbnail-suffix: ".min.jpg" #缩略图后缀，例如【.min.jpg】【.png】
    huawei-obs:
      - platform: huawei-obs-1 # 存储平台标识
        enable-storage: false  # 启用存储
        access-key: ??
        secret-key: ??
        end-point: ??
        bucket-name: ??
        domain: ?? # 访问域名，注意“/”结尾，例如：http://abc.obs.com/
        base-path: test/ # 基础路径
      - platform: huawei-obs-2 # 存储平台标识，这与这里不能重复
        enable-storage: false  # 启用存储
        access-key: ??
        secret-key: ??
        end-point: ??
        bucket-name: ??
        domain: ?? # 访问域名，注意“/”结尾，例如：http://abc.obs.com/
        base-path: test2/ # 基础路径
    aliyun-oss:
      - platform: aliyun-oss-1 # 存储平台标识
        enable-storage: false  # 启用存储
        access-key: ??
        secret-key: ??
        end-point: ??
        bucket-name: ??
        domain: ?? # 访问域名，注意“/”结尾，例如：https://abc.oss-cn-shanghai.aliyuncs.com/
        base-path: test/ # 基础路径
    fastdfs:
      - platform: fastdfs-1 # 存储平台标识
        enable-storage: true  # 启用存储
        run-mod: COVER #运行模式，默认 COVER（覆盖模式），强制用 FastDFS 返回的路径及文件名覆盖 FileInfo 中的 path 及 filename。
        tracker-server: # Tracker Server 配置
          server-addr: ?? # Tracker Server 地址（IP:PORT），多个用英文逗号隔开
        domain: ?? # 访问域名，注意“/”结尾，例如：https://file.abc.com/
        base-path: "" # 基础路径，强烈建议留空，详情查看兼容性说明章节
    qiniu-kodo:
      - platform: qiniu-kodo-1 # 存储平台标识
        enable-storage: false  # 启用存储
        access-key: ??
        secret-key: ??
        bucket-name: ??
        domain: ??
        # 访问域名，注意“/”结尾，例如：http://abc.hn-bkt.clouddn.com/
        base-path:  # 基础路径
    amazon-s3: # Amazon S3 天翼云也在此配置
      - platform: amazon-s3-1 # 存储平台标识
        enable-storage: true  # 启用存储
        access-key: xxxx
        secret-key: xxxxx
        end-point: https://xian7.zos.ctyun.cn/ # 与 region 参数至少填一个
        bucket-name: bucket-xxxx #桶名称
        domain: https://bucket-xxxx.xian7.zos.ctyun.cn/ # 访问域名，注意“/”结尾，例如：https://abcd.s3.ap-east-1.amazonaws.com/
        base-path:  # 基础路径
migration:
  task-type: file # 可选值：file、data、all
  mode: test # 迁移模式，可选值：test、prod test模式只会迁移一批次数据
  batch-size: 1000
  retry-count: 3   # 添加重试次数配置
  file-migration:
    origin-platform: fastdfs-1
    destination-platform: amazon-s3-1
